name: build

on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹Workflow 2 which will be triggered'
        required: true
        default: 'workflow_02'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'faroukbr'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: 'terraformDeploy' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/testing-app-terraform:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/testing-app-terraform:latest
      - name: Trigging
        run: |
          curl -X POST https://api.github.com/repos/faroukbr/terraformDeploy/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.G_ACCESS_TOKEN }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v4
      - name: Deploy Web App
        run: |
          echo "the infrastructure was provisioning in the Deploy Repo and the app will deploy"
          sleep 10s

