name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/testing-app-terraform:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/testing-app-terraform:latest
      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: keithweaver
          repo: terraformDeploy
          ref: main
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: deploy.yml
          trigger_workflow: true
          wait_workflow: true
          
      - name: Deploy Web App
        run: |
          echo "the infrastructure was provisioning in the Deploy Repo and the app will deploy"
          sleep 10s
